folly: connect up badge tests to cmake
Fails for me with GCC 11.2.1:

$ ./build/fbcode_builder/getdeps.py --allow-system-packages build
Thu 16 Dec 20:38:26 GMT 2021
Building on {distro=fedora, distro_vers=35, fb=off, os=linux, test=on}
Testing ENV[BOOST_ROOT_1_69_0]: None
Assessing fmt...
Assessing gflags...
Assessing glog...
Assessing googletest...
Assessing snappy...
Assessing folly...
Testing ENV[BOOST_ROOT_1_69_0]: None
Building folly...
[1/3] Building CXX object CMakeFiles/lang_badge_test.dir/folly/lang/test/BadgeTest.cpp.o
FAILED: CMakeFiles/lang_badge_test.dir/folly/lang/test/BadgeTest.cpp.o
/usr/bin/c++ -DFMT_LOCALE -DFOLLY_XLOG_STRIP_PREFIXES=\"/home/alex/local/folly:/tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/build/folly\" -DGFLAGS_IS_A_DLL=0 -D_GNU_SOURCE -D_REENTRANT -I/home/alex/local/folly -I/tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/build/folly -I/tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/installed/glog-AG9U9DdoN4UC-w5LRqJJKCx07nF8vzD-d0ng5gFbKdc/include -I/tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/installed/snappy-4tzr-Oo-Ri9sTq0giSBs2tAqmAMq1ECEfLWTr5u5kbQ/include -isystem /tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/installed/googletest-22rMap9OSotkIErqOrdwBybO2YQn9CdiOmLJlm-TPY4/include -isystem /tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/installed/gflags-LB3W6wcPFj0OUuT48OTOfw1Ooi2OR-nKYZSneSOfSUE/include -isystem /tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/installed/fmt-xy32UcZ4gxRl6P5ubdEb43Xs99Rm3XJOlEDBImviIFs/include -O2 -g -DNDEBUG -fcoroutines -g -std=gnu++1z -finput-charset=UTF-8 -fsigned-char -Wall -Wno-deprecated -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused -Wunused-label -Wunused-result -Wshadow-compatible-local -Wno-noexcept-type -faligned-new -fopenmp -std=gnu++17 -MD -MT CMakeFiles/lang_badge_test.dir/folly/lang/test/BadgeTest.cpp.o -MF CMakeFiles/lang_badge_test.dir/folly/lang/test/BadgeTest.cpp.o.d -o CMakeFiles/lang_badge_test.dir/folly/lang/test/BadgeTest.cpp.o -c /home/alex/local/folly/folly/lang/test/BadgeTest.cpp
In file included from /home/alex/local/folly/folly/lang/test/BadgeTest.cpp:19:
/home/alex/local/folly/folly/lang/Badge.h: In instantiation of ‘class folly::any_badge<{anonymous}::FriendClass, {anonymous}::OtherFriendClass>’:
/home/alex/local/folly/folly/lang/test/BadgeTest.cpp:38:40:   required from here
/home/alex/local/folly/folly/lang/Badge.h:99:18: error: expansion pattern ‘folly::StrictDisjunction<std::is_same<OtherHolders, Holders>...>’ contains no parameter packs
   99 |   /* implicit */ any_badge(any_badge<OtherHolders...>) noexcept {}
      |                  ^~~~~~~~~
/home/alex/local/folly/folly/lang/Badge.h: In instantiation of ‘class folly::any_badge<{anonymous}::FriendClass, {anonymous}::OtherFriendClass, {anonymous}::DummyClass>’:
/home/alex/local/folly/folly/lang/test/BadgeTest.cpp:39:53:   required from here
/home/alex/local/folly/folly/lang/Badge.h:99:18: error: expansion pattern ‘folly::StrictDisjunction<std::is_same<OtherHolders, Holders>...>’ contains no parameter packs
/home/alex/local/folly/folly/lang/test/BadgeTest.cpp: In static member function ‘static void {anonymous}::ProtectedClass::subset({anonymous}::SubsetBadges)’:
/home/alex/local/folly/folly/lang/test/BadgeTest.cpp:39:54: error: cannot convert ‘any_badge<{anonymous}::FriendClass, {anonymous}::OtherFriendClass>’ to ‘any_badge<{anonymous}::FriendClass, {anonymous}::OtherFriendClass, {anonymous}::DummyClass>’
   39 |   static void subset(SubsetBadges badges) { superset(badges); }
      |                                                      ^~~~~~
      |                                                      |
      |                                                      any_badge<{anonymous}::FriendClass, {anonymous}::OtherFriendClass>
/home/alex/local/folly/folly/lang/test/BadgeTest.cpp:40:24: note:   initializing argument 1 of ‘static void {anonymous}::ProtectedClass::superset({anonymous}::SupersetBadges)’
   40 |   static void superset(SupersetBadges) {}
      |                        ^~~~~~~~~~~~~~
In file included from /home/alex/local/folly/folly/lang/test/BadgeTest.cpp:19:
/home/alex/local/folly/folly/lang/Badge.h: In instantiation of ‘class folly::any_badge<{anonymous}::FriendClass>’:
/home/alex/local/folly/folly/lang/test/BadgeTest.cpp:47:35:   required from here
/home/alex/local/folly/folly/lang/Badge.h:99:18: error: expansion pattern ‘folly::StrictDisjunction<std::is_same<OtherHolders, Holders>...>’ contains no parameter packs
   99 |   /* implicit */ any_badge(any_badge<OtherHolders...>) noexcept {}
      |                  ^~~~~~~~~
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/tmp/fbcode_builder_getdeps-ZhomeZalexZlocalZfollyZbuildZfbcode_builder/build/folly', '--target', 'install', '--config', 'Release', '-j', '16']' returned non-zero exit status 1.
!! Failed